support terminal width detection
vito/go-interact pull request #5
Opened 2017-04-04 18:00 UTC by XenoPhex

- Updated `ssh/terminal`
- Repatched `Ctrl`+`C` functionality
- Added auto width detection because always cutting the message off at 80 characters was weird. This fixes it in TTY sessions only.

2017-04-26 18:18 UTC, vito requested changes

2017-04-26 18:18 UTC, vito commented on interact/userio.go
> +func (u ttyUser) detectTerminalSize(file *os.File) error {
could you move this logic into the constructor instead by having the constructor take the `file`? i don't like that this private method is alongside other public methods, but only ever called by the person constructing the object.

2017-04-28 02:44 UTC, XenoPhex commented
@vito changes made!

2017-04-28 12:21 UTC, vito approved these changes

2017-04-28 12:21 UTC, vito commented
Thanks!

2017-04-28 12:21 UTC, merged